# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  gainsway:
    type: nuget-feed
    url: https://nuget.pkg.github.com/gainsway/index.json
    username: gainsway
    password: ${{ secrets.NUGET_TOKEN }}

updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "dont-check-PRs-with-this-label"
      - "dependencies"
  - package-ecosystem: "nuget"
    registries:
      - nuget
      - gainsway
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "dont-check-PRs-with-this-label"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dont-check-PRs-with-this-label"
      - "dependencies"
