name: pr-checker

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-checker:
    permissions:
      contents: read
      pull-requests: write
    uses: gainsway/github-workflows-public/.github/workflows/job.pr-checker.yml@main
