name: pr-checker
on:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  pr-checker:
    permissions:
      contents: write
      pull-requests: write
    uses: gainsway/github-workflows-public/.github/workflows/job.pr-checker.yml@main
